export const mockDataConfig = {
  monthlyServiceSuccess: [
    { name: "Completed", value: 68, fill: "#22c55e" },
    { name: "Pending", value: 32, fill: "#ef4444" },
  ],

  monthlyBreakdownSuccess: [
    { name: "Completed", value: 55, fill: "#3b82f6" },
    { name: "Pending", value: 45, fill: "#f59e0b" },
  ],

  technicianSummaryData: [
    { date: "Mon", services: 12, breakdowns: 8, completed: 15 },
    { date: "Tue", services: 14, breakdowns: 10, completed: 18 },
    { date: "Wed", services: 10, breakdowns: 12, completed: 16 },
    { date: "Thu", services: 16, breakdowns: 7, completed: 19 },
    { date: "Fri", services: 18, breakdowns: 11, completed: 22 },
    { date: "Sat", services: 8, breakdowns: 5, completed: 11 },
    { date: "Sun", services: 6, breakdowns: 3, completed: 7 },
  ],

  technicianPerformance: [
    { id: "TECH001", name: "John Silva", completedJobs: 156, rating: 4.8, services: 98, breakdowns: 58 },
    { id: "TECH002", name: "Priya Sharma", completedJobs: 142, rating: 4.7, services: 87, breakdowns: 55 },
    { id: "TECH003", name: "Miguel Fernandez", completedJobs: 138, rating: 4.6, services: 82, breakdowns: 56 },
    { id: "TECH004", name: "Sarah Johnson", completedJobs: 131, rating: 4.5, services: 78, breakdowns: 53 },
    { id: "TECH005", name: "Ahmed Hassan", completedJobs: 128, rating: 4.4, services: 76, breakdowns: 52 },
  ],

  pendingJobs: [
    { id: "JOB001", technician: "John Silva", jobType: "Service", location: "Colombo", daysLeft: 2 },
    { id: "JOB002", technician: "Priya Sharma", jobType: "Breakdown", location: "Kandy", daysLeft: 1 },
    { id: "JOB003", technician: "Miguel Fernandez", jobType: "Service", location: "Galle", daysLeft: 3 },
  ],

  warrantyDetailsData: [
    {
      cusName: "ABC Corporation",
      invAdd1: "123 Main St",
      invAdd2: "Suite 100",
      invAdd3: "Colombo",
      serialNo: "SN-001",
      machineDesc: "MP5054 Copier",
      machineRefCode: "REF-001",
      team: "Team A",
      cusStatus: "Active",
      tOfficerCode: "TO001",
      tOfficerName: "John Silva",
      maPeriodEnd: "2024-12-31",
      mWarrantyEndDate: "2024-12-31",
    },
    {
      cusName: "XYZ Industries",
      invAdd1: "456 Oak Ave",
      invAdd2: "Suite 200",
      invAdd3: "Kandy",
      serialNo: "SN-002",
      machineDesc: "MP2851 Printer",
      machineRefCode: "REF-002",
      team: "Team B",
      cusStatus: "Active",
      tOfficerCode: "TO002",
      tOfficerName: "Priya Sharma",
      maPeriodEnd: "2024-11-30",
      mWarrantyEndDate: "2024-11-30",
    },
    {
      cusName: "Tech Solutions Ltd",
      invAdd1: "789 Pine Rd",
      invAdd2: "Suite 300",
      invAdd3: "Galle",
      serialNo: "SN-003",
      machineDesc: "MP3500 Scanner",
      machineRefCode: "REF-003",
      team: "Team C",
      cusStatus: "Inactive",
      tOfficerCode: "TO003",
      tOfficerName: "Miguel Fernandez",
      maPeriodEnd: "2024-10-31",
      mWarrantyEndDate: "2024-10-31",
    },
    {
      cusName: "Global Corp",
      invAdd1: "101 Elm St",
      invAdd2: "Suite 400",
      invAdd3: "Jaffna",
      serialNo: "SN-004",
      machineDesc: "MP6054 Copier",
      machineRefCode: "REF-004",
      team: "Team A",
      cusStatus: "Active",
      tOfficerCode: "TO001",
      tOfficerName: "John Silva",
      maPeriodEnd: "2024-09-30",
      mWarrantyEndDate: "2024-09-30",
    },
    {
      cusName: "Future Tech",
      invAdd1: "202 Birch Ln",
      invAdd2: "Suite 500",
      invAdd3: "Matara",
      serialNo: "SN-005",
      machineDesc: "MP8054 Multifunction",
      machineRefCode: "REF-005",
      team: "Team B",
      cusStatus: "Active",
      tOfficerCode: "TO002",
      tOfficerName: "Priya Sharma",
      maPeriodEnd: "2024-08-31",
      mWarrantyEndDate: "2024-08-31",
    },
  ],

  warrantySummaryData: [
    { tOfficerCode: "TO001", tOfficerName: "John Silva", team: "Team A", machineCount: 45 },
    { tOfficerCode: "TO002", tOfficerName: "Priya Sharma", team: "Team B", machineCount: 38 },
    { tOfficerCode: "TO003", tOfficerName: "Miguel Fernandez", team: "Team C", machineCount: 32 },
    { tOfficerCode: "TO004", tOfficerName: "Sarah Johnson", team: "Team D", machineCount: 41 },
    { tOfficerCode: "TO005", tOfficerName: "Ahmed Hassan", team: "Team A", machineCount: 29 },
  ],

breakdownJobs: [
  {
    id: "BRK001",
    jobNumber: "JOB-001",
    type: "breakdown",
    
    qNumber: "Q-00001",
    serialNumber: "SN-123456",
    machineRef: "MP-5054",
    status: "pending",
    note: "Machine not functioning",
    team: "Team A",
    col: "COL-001",
    informBy: "phone",
    informType: "urgent",
    customer: "ABC Corporation",
    address1: "123 Main St",
    address2: "Colombo",
    address3: "Western Province",
    contact: "+94-11-2345678",
    model: "MP5054",
    sms: false,
    techCode: "TECH001",
    techMobile: "+94-701234567",
  },
  {
    id: "BRK002",
    jobNumber: "JOB-002",
    qNumber: "Q-00002",
    serialNumber: "SN-789012",
    machineRef: "MP-2851",
    status: "assigned",
    note: "Paper jam issue",
    team: "Team B",
    col: "COL-002",
    informBy: "email",
    informType: "normal",
    customer: "XYZ Industries",
    address1: "456 Oak Ave",
    address2: "Kandy",
    address3: "Central Province",
    contact: "+94-81-2345678",
    model: "MP2851",
    sms: true,
    techCode: "TECH002",
    techMobile: "+94-701234568",
  },

  // 🔹 Added 20 records
  {
    id: "BRK003",
    jobNumber: "JOB-003",
    qNumber: "Q-00003",
    serialNumber: "SN-345678",
    machineRef: "MP-4020",
    status: "pending",
    note: "Toner leakage detected",
    team: "Team A",
    col: "COL-003",
    informBy: "phone",
    informType: "urgent",
    customer: "Lanka Traders",
    address1: "78 Market Rd",
    address2: "Negombo",
    address3: "Western Province",
    contact: "+94-31-2233445",
    model: "MP4020",
    sms: "false",
    techCode: "TECH003",
    techMobile: "+94-701234569",
  },
  {
    id: "BRK004",
    jobNumber: "JOB-004",
    qNumber: "Q-00004",
    serialNumber: "SN-456789",
    machineRef: "MP-3201",
    status: "completed",
    note: "Display panel not responding",
    team: "Team C",
    col: "COL-004",
    informBy: "email",
    informType: "normal",
    customer: "Oceanic Exports",
    address1: "45 Harbor Rd",
    address2: "Matara",
    address3: "Southern Province",
    contact: "+94-41-2233445",
    model: "MP3201",
    sms: true,
    techCode: "TECH004",
    techMobile: "+94-701234570",
  },
  {
    id: "BRK005",
    jobNumber: "JOB-005",
    qNumber: "Q-00005",
    serialNumber: "SN-567890",
    machineRef: "MP-5054",
    status: "assigned",
    note: "Network printing not working",
    team: "Team B",
    col: "COL-005",
    informBy: "phone",
    informType: "normal",
    customer: "City Hospital",
    address1: "12 Health St",
    address2: "Colombo",
    address3: "Western Province",
    contact: "+94-11-2987654",
    model: "MP5054",
    sms: true,
    techCode: "TECH005",
    techMobile: "+94-701234571",
  },
  {
    id: "BRK006",
    jobNumber: "JOB-006",
    qNumber: "Q-00006",
    serialNumber: "SN-678901",
    machineRef: "MP-3900",
    status: "pending",
    note: "Abnormal noise during printing",
    team: "Team D",
    col: "COL-006",
    informBy: "email",
    informType: "urgent",
    customer: "Royal Printing Works",
    address1: "90 Station Rd",
    address2: "Ratnapura",
    address3: "Sabaragamuwa Province",
    contact: "+94-45-2233445",
    model: "MP3900",
    sms: false,
    techCode: "TECH006",
    techMobile: "+94-701234572",
  },
  {
    id: "BRK007",
    jobNumber: "JOB-007",
    qNumber: "Q-00007",
    serialNumber: "SN-789123",
    machineRef: "MP-2750",
    status: "assigned",
    note: "Scanner not detecting documents",
    team: "Team A",
    col: "COL-007",
    informBy: "phone",
    informType: "normal",
    customer: "Bright Education Center",
    address1: "34 School Ln",
    address2: "Anuradhapura",
    address3: "North Central Province",
    contact: "+94-25-2233445",
    model: "MP2750",
    sms: true,
    techCode: "TECH007",
    techMobile: "+94-701234573",
  },
  {
    id: "BRK008",
    jobNumber: "JOB-008",
    qNumber: "Q-00008",
    serialNumber: "SN-890234",
    machineRef: "MP-3600",
    status: "completed",
    note: "Print quality faded",
    team: "Team C",
    col: "COL-008",
    informBy: "email",
    informType: "normal",
    customer: "Northern Textiles",
    address1: "11 Factory Rd",
    address2: "Jaffna",
    address3: "Northern Province",
    contact: "+94-21-2233445",
    model: "MP3600",
    sms: false,
    techCode: "TECH008",
    techMobile: "+94-701234574",
  },
  {
    id: "BRK009",
    jobNumber: "JOB-009",
    qNumber: "Q-00009",
    serialNumber: "SN-901345",
    machineRef: "MP-4200",
    status: "pending",
    note: "Error code displayed on startup",
    team: "Team B",
    col: "COL-009",
    informBy: "phone",
    informType: "urgent",
    customer: "Digital Office Solutions",
    address1: "66 Tech Park",
    address2: "Batticaloa",
    address3: "Eastern Province",
    contact: "+94-65-2233445",
    model: "MP4200",
    sms: true,
    techCode: "TECH009",
    techMobile: "+94-701234575",
  },
  {
    id: "BRK010",
    jobNumber: "JOB-010",
    qNumber: "Q-00010",
    serialNumber: "SN-012456",
    machineRef: "MP-5054",
    status: "assigned",
    note: "Fuser unit overheating",
    team: "Team D",
    col: "COL-010",
    informBy: "email",
    informType: "urgent",
    customer: "Metro Supermarket",
    address1: "22 Market Sq",
    address2: "Kalutara",
    address3: "Western Province",
    contact: "+94-34-2233445",
    model: "MP5054",
    sms: false,
    techCode: "TECH010",
    techMobile: "+94-701234576",
  },

  // ... BRK011 → BRK022 (20 new total)
],


serviceScheduleRecallJobs: [
  {
    id: "SCHED001",
    type: "service",
    jobId: "SVC-2024-001",
    customerName: "ABC Corporation",
    location: "Colombo",
    date: "2024-01-15",
    machineRef: "MP-5054",
    technician: "John Silva",
    status: "pending",
  },
  {
    id: "SCHED002",
    type: "breakdown",
    jobId: "BRK-2024-012",
    customerName: "XYZ Industries",
    location: "Kandy",
    date: "2024-01-16",
    machineRef: "MP-2851",
    technician: "Priya Sharma",
    status: "pending",
  },
  {
    id: "SCHED003",
    type: "service",
    jobId: "SVC-2024-002",
    customerName: "Tech Solutions Ltd",
    location: "Galle",
    date: "2024-01-17",
    machineRef: "MP-5054",
    technician: "Miguel Fernandez",
    status: "pending",
  },

  // 🔹 Added 10 more records
  {
    id: "SCHED004",
    type: "service",
    jobId: "SVC-2024-003",
    customerName: "Lanka Traders",
    location: "Negombo",
    date: "2024-01-18",
    machineRef: "MP-4020",
    technician: "Kasun Perera",
    status: "pending",
  },
  {
    id: "SCHED005",
    type: "breakdown",
    jobId: "BRK-2024-013",
    customerName: "Green Farm Pvt Ltd",
    location: "Kurunegala",
    date: "2024-01-18",
    machineRef: "MP-3201",
    technician: "Nimal Jayasinghe",
    status: "pending",
  },
  {
    id: "SCHED006",
    type: "service",
    jobId: "SVC-2024-004",
    customerName: "Oceanic Exports",
    location: "Matara",
    date: "2024-01-19",
    machineRef: "MP-5054",
    technician: "Ruwan Silva",
    status: "pending",
  },
  {
    id: "SCHED007",
    type: "breakdown",
    jobId: "BRK-2024-014",
    customerName: "City Hospital",
    location: "Colombo",
    date: "2024-01-19",
    machineRef: "MP-4100",
    technician: "Saman Kumara",
    status: "pending",
  },
  {
    id: "SCHED008",
    type: "service",
    jobId: "SVC-2024-005",
    customerName: "Bright Education Center",
    location: "Anuradhapura",
    date: "2024-01-20",
    machineRef: "MP-2851",
    technician: "Chathura Fernando",
    status: "pending",
  },
  {
    id: "SCHED009",
    type: "service",
    jobId: "SVC-2024-006",
    customerName: "Northern Textiles",
    location: "Jaffna",
    date: "2024-01-20",
    machineRef: "MP-3900",
    technician: "Arun Kumar",
    status: "pending",
  },
  {
    id: "SCHED010",
    type: "breakdown",
    jobId: "BRK-2024-015",
    customerName: "Metro Supermarket",
    location: "Kalutara",
    date: "2024-01-21",
    machineRef: "MP-2750",
    technician: "Dinesh Weerasinghe",
    status: "pending",
  },
  {
    id: "SCHED011",
    type: "service",
    jobId: "SVC-2024-007",
    customerName: "Royal Printing Works",
    location: "Ratnapura",
    date: "2024-01-21",
    machineRef: "MP-5054",
    technician: "Tharindu Madushan",
    status: "pending",
  },
  {
    id: "SCHED012",
    type: "breakdown",
    jobId: "BRK-2024-016",
    customerName: "Sunrise Garments",
    location: "Avissawella",
    date: "2024-01-22",
    machineRef: "MP-3600",
    technician: "Isuru Bandara",
    status: "pending",
  },
  {
    id: "SCHED013",
    type: "service",
    jobId: "SVC-2024-008",
    customerName: "Digital Office Solutions",
    location: "Batticaloa",
    date: "2024-01-22",
    machineRef: "MP-4200",
    technician: "Mohamed Rizwan",
    status: "pending",
  },
],


technicianBreakdowns:[
  { id: "207940", jobId: "207940", date: "2026-01-21", location: "Wadduwa", description: "Machine not powering on", status: "started", customer_agreement: "Free Service" },
  { id: "207941", jobId: "207941", date: "2026-01-20", location: "Colombo", description: "Replace faulty motor", status: "pending", customer_agreement: "Maintaines Agrement" },
  { id: "207942", jobId: "207942", date: "2026-01-19", location: "Galle", description: "Oil leakage issue", status: "completed", customer_agreement: "Extend Service" },
  { id: "207943", jobId: "207943", date: "2026-01-18", location: "Negombo", description: "Routine maintenance", status: "started", customer_agreement: "No Service" },
  { id: "207944", jobId: "207944", date: "2026-01-17", location: "Kalutara", description: "Check overheating problem", status: "pending", customer_agreement: "Free Service" },
  { id: "207945", jobId: "207945", date: "2026-01-16", location: "Matara", description: "Replace damaged belt", status: "completed", customer_agreement: "Maintaines Agrement" },
  { id: "207946", jobId: "207946", date: "2026-01-15", location: "Panadura", description: "Software update required", status: "started", customer_agreement: "Extend Service" },
  { id: "207947", jobId: "207947", date: "2026-01-14", location: "Moratuwa", description: "Motor noise issue", status: "pending", customer_agreement: "No Service" },
  { id: "207948", jobId: "207948", date: "2026-01-13", location: "Ratnapura", description: "Replace control panel", status: "completed", customer_agreement: "Free Service" },
  { id: "207949", jobId: "207949", date: "2026-01-12", location: "Kandy", description: "Check power supply", status: "started", customer_agreement: "Maintaines Agrement" },
  { id: "207950", jobId: "207950", date: "2026-01-11", location: "Jaffna", description: "Routine inspection", status: "pending", customer_agreement: "Extend Service" },
  { id: "207951", jobId: "207951", date: "2026-01-10", location: "Anuradhapura", description: "Replace worn-out parts", status: "completed", customer_agreement: "No Service" },
  { id: "207952", jobId: "207952", date: "2026-01-09", location: "Trincomalee", description: "Temperature sensor issue", status: "started", customer_agreement: "Free Service" },
  { id: "207953", jobId: "207953", date: "2026-01-08", location: "Hambantota", description: "Replace faulty wiring", status: "pending", customer_agreement: "Maintaines Agrement" },
  { id: "207954", jobId: "207954", date: "2026-01-07", location: "Badulla", description: "Lubrication required", status: "completed", customer_agreement: "Extend Service" },
  { id: "207955", jobId: "207955", date: "2026-01-06", location: "Nuwara Eliya", description: "Cooling fan issue", status: "started", customer_agreement: "No Service" },
  { id: "207956", jobId: "207956", date: "2026-01-05", location: "Puttalam", description: "Voltage fluctuation detected", status: "pending", customer_agreement: "Free Service" },
  { id: "207957", jobId: "207957", date: "2026-01-04", location: "Kurunegala", description: "Replace broken switch", status: "completed", customer_agreement: "Maintaines Agrement" },
  { id: "207958", jobId: "207958", date: "2026-01-03", location: "Polonnaruwa", description: "Routine checkup", status: "started", customer_agreement: "Extend Service" },
  { id: "207959", jobId: "207959", date: "2026-01-02", location: "Monaragala", description: "Fix hydraulic issue", status: "pending", customer_agreement: "No Service" }
],


  technicianServices: [
  { id: "SVC001", jobId: "Q454545", customerName: "Sugath de Silva", date: "2026-01-15", location: "Kandy", daysLeft: 5, status: "started", expected_visit_no: 1 },
  { id: "SVC002", jobId: "Q454546", customerName: "Nadeesha Fernando", date: "2026-01-16", location: "Colombo", daysLeft: 3, status: "pending", expected_visit_no: 2 },
  { id: "SVC003", jobId: "Q454547", customerName: "Chamara Perera", date: "2026-01-17", location: "Galle", daysLeft: 7, status: "completed", expected_visit_no: 1 },
  { id: "SVC004", jobId: "Q454548", customerName: "Kamal Rajapaksha", date: "2026-01-18", location: "Negombo", daysLeft: 2, status: "started", expected_visit_no: 3 },
  { id: "SVC005", jobId: "Q454549", customerName: "Dinithi Jayawardena", date: "2026-01-19", location: "Matara", daysLeft: 4, status: "pending", expected_visit_no: 2 },
  { id: "SVC006", jobId: "Q454550", customerName: "Roshan Silva", date: "2026-01-20", location: "Kalutara", daysLeft: 6, status: "completed", expected_visit_no: 4 },
  { id: "SVC007", jobId: "Q454551", customerName: "Iresha Perera", date: "2026-01-21", location: "Panadura", daysLeft: 1, status: "started", expected_visit_no: 1 },
  { id: "SVC008", jobId: "Q454552", customerName: "Saman Kumara", date: "2026-01-22", location: "Ratnapura", daysLeft: 8, status: "pending", expected_visit_no: 5 },
  { id: "SVC009", jobId: "Q454553", customerName: "Tharindu Silva", date: "2026-01-23", location: "Jaffna", daysLeft: 3, status: "completed", expected_visit_no: 2 },
  { id: "SVC010", jobId: "Q454554", customerName: "Dilani Perera", date: "2026-01-24", location: "Anuradhapura", daysLeft: 5, status: "started", expected_visit_no: 6 }
],
}
