export const mockDataConfig = {
  monthlyServiceSuccess: [
    { name: "Completed", value: 68, fill: "#22c55e" },
    { name: "Pending", value: 32, fill: "#ef4444" },
  ],

  monthlyBreakdownSuccess: [
    { name: "Completed", value: 55, fill: "#3b82f6" },
    { name: "Pending", value: 45, fill: "#f59e0b" },
  ],

  technicianSummaryData: [
    { date: "Mon", services: 12, breakdowns: 8, completed: 15 },
    { date: "Tue", services: 14, breakdowns: 10, completed: 18 },
    { date: "Wed", services: 10, breakdowns: 12, completed: 16 },
    { date: "Thu", services: 16, breakdowns: 7, completed: 19 },
    { date: "Fri", services: 18, breakdowns: 11, completed: 22 },
    { date: "Sat", services: 8, breakdowns: 5, completed: 11 },
    { date: "Sun", services: 6, breakdowns: 3, completed: 7 },
  ],

  technicianPerformance: [
    { id: "TECH001", name: "John Silva", completedJobs: 156, rating: 4.8, services: 98, breakdowns: 58 },
    { id: "TECH002", name: "Priya Sharma", completedJobs: 142, rating: 4.7, services: 87, breakdowns: 55 },
    { id: "TECH003", name: "Miguel Fernandez", completedJobs: 138, rating: 4.6, services: 82, breakdowns: 56 },
    { id: "TECH004", name: "Sarah Johnson", completedJobs: 131, rating: 4.5, services: 78, breakdowns: 53 },
    { id: "TECH005", name: "Ahmed Hassan", completedJobs: 128, rating: 4.4, services: 76, breakdowns: 52 },
  ],

  pendingJobs: [
    { id: "JOB001", technician: "John Silva", jobType: "Service", location: "Colombo", daysLeft: 2 },
    { id: "JOB002", technician: "Priya Sharma", jobType: "Breakdown", location: "Kandy", daysLeft: 1 },
    { id: "JOB003", technician: "Miguel Fernandez", jobType: "Service", location: "Galle", daysLeft: 3 },
  ],

  warrantyDetailsData: [
    {
      cusName: "ABC Corporation",
      invAdd1: "123 Main St",
      invAdd2: "Suite 100",
      invAdd3: "Colombo",
      serialNo: "SN-001",
      machineDesc: "MP5054 Copier",
      machineRefCode: "REF-001",
      team: "Team A",
      cusStatus: "Active",
      tOfficerCode: "TO001",
      tOfficerName: "John Silva",
      maPeriodEnd: "2024-12-31",
      mWarrantyEndDate: "2024-12-31",
    },
    {
      cusName: "XYZ Industries",
      invAdd1: "456 Oak Ave",
      invAdd2: "Suite 200",
      invAdd3: "Kandy",
      serialNo: "SN-002",
      machineDesc: "MP2851 Printer",
      machineRefCode: "REF-002",
      team: "Team B",
      cusStatus: "Active",
      tOfficerCode: "TO002",
      tOfficerName: "Priya Sharma",
      maPeriodEnd: "2024-11-30",
      mWarrantyEndDate: "2024-11-30",
    },
    {
      cusName: "Tech Solutions Ltd",
      invAdd1: "789 Pine Rd",
      invAdd2: "Suite 300",
      invAdd3: "Galle",
      serialNo: "SN-003",
      machineDesc: "MP3500 Scanner",
      machineRefCode: "REF-003",
      team: "Team C",
      cusStatus: "Inactive",
      tOfficerCode: "TO003",
      tOfficerName: "Miguel Fernandez",
      maPeriodEnd: "2024-10-31",
      mWarrantyEndDate: "2024-10-31",
    },
    {
      cusName: "Global Corp",
      invAdd1: "101 Elm St",
      invAdd2: "Suite 400",
      invAdd3: "Jaffna",
      serialNo: "SN-004",
      machineDesc: "MP6054 Copier",
      machineRefCode: "REF-004",
      team: "Team A",
      cusStatus: "Active",
      tOfficerCode: "TO001",
      tOfficerName: "John Silva",
      maPeriodEnd: "2024-09-30",
      mWarrantyEndDate: "2024-09-30",
    },
    {
      cusName: "Future Tech",
      invAdd1: "202 Birch Ln",
      invAdd2: "Suite 500",
      invAdd3: "Matara",
      serialNo: "SN-005",
      machineDesc: "MP8054 Multifunction",
      machineRefCode: "REF-005",
      team: "Team B",
      cusStatus: "Active",
      tOfficerCode: "TO002",
      tOfficerName: "Priya Sharma",
      maPeriodEnd: "2024-08-31",
      mWarrantyEndDate: "2024-08-31",
    },
  ],

  warrantySummaryData: [
    { tOfficerCode: "TO001", tOfficerName: "John Silva", team: "Team A", machineCount: 45 },
    { tOfficerCode: "TO002", tOfficerName: "Priya Sharma", team: "Team B", machineCount: 38 },
    { tOfficerCode: "TO003", tOfficerName: "Miguel Fernandez", team: "Team C", machineCount: 32 },
    { tOfficerCode: "TO004", tOfficerName: "Sarah Johnson", team: "Team D", machineCount: 41 },
    { tOfficerCode: "TO005", tOfficerName: "Ahmed Hassan", team: "Team A", machineCount: 29 },
  ],

breakdownJobs: [
  {
    id: "BRK001",
    jobNumber: "JOB-001",
    type: "breakdown",
    
    qNumber: "Q-00001",
    serialNumber: "SN-123456",
    machineRef: "MP-5054",
    status: "pending",
    note: "Machine not functioning",
    team: "Team A",
    col: "COL-001",
    informBy: "phone",
    informType: "urgent",
    customer: "ABC Corporation",
    address1: "123 Main St",
    address2: "Colombo",
    address3: "Western Province",
    contact: "+94-11-2345678",
    model: "MP5054",
    sms: false,
    techCode: "TECH001",
    techMobile: "+94-701234567",
  },
  {
    id: "BRK002",
    jobNumber: "JOB-002",
    qNumber: "Q-00002",
    serialNumber: "SN-789012",
    machineRef: "MP-2851",
    status: "assigned",
    note: "Paper jam issue",
    team: "Team B",
    col: "COL-002",
    informBy: "email",
    informType: "normal",
    customer: "XYZ Industries",
    address1: "456 Oak Ave",
    address2: "Kandy",
    address3: "Central Province",
    contact: "+94-81-2345678",
    model: "MP2851",
    sms: true,
    techCode: "TECH002",
    techMobile: "+94-701234568",
  },

  // 🔹 Added 20 records
  {
    id: "BRK003",
    jobNumber: "JOB-003",
    qNumber: "Q-00003",
    serialNumber: "SN-345678",
    machineRef: "MP-4020",
    status: "pending",
    note: "Toner leakage detected",
    team: "Team A",
    col: "COL-003",
    informBy: "phone",
    informType: "urgent",
    customer: "Lanka Traders",
    address1: "78 Market Rd",
    address2: "Negombo",
    address3: "Western Province",
    contact: "+94-31-2233445",
    model: "MP4020",
    sms: "false",
    techCode: "TECH003",
    techMobile: "+94-701234569",
  },
  {
    id: "BRK004",
    jobNumber: "JOB-004",
    qNumber: "Q-00004",
    serialNumber: "SN-456789",
    machineRef: "MP-3201",
    status: "completed",
    note: "Display panel not responding",
    team: "Team C",
    col: "COL-004",
    informBy: "email",
    informType: "normal",
    customer: "Oceanic Exports",
    address1: "45 Harbor Rd",
    address2: "Matara",
    address3: "Southern Province",
    contact: "+94-41-2233445",
    model: "MP3201",
    sms: true,
    techCode: "TECH004",
    techMobile: "+94-701234570",
  },
  {
    id: "BRK005",
    jobNumber: "JOB-005",
    qNumber: "Q-00005",
    serialNumber: "SN-567890",
    machineRef: "MP-5054",
    status: "assigned",
    note: "Network printing not working",
    team: "Team B",
    col: "COL-005",
    informBy: "phone",
    informType: "normal",
    customer: "City Hospital",
    address1: "12 Health St",
    address2: "Colombo",
    address3: "Western Province",
    contact: "+94-11-2987654",
    model: "MP5054",
    sms: true,
    techCode: "TECH005",
    techMobile: "+94-701234571",
  },
  {
    id: "BRK006",
    jobNumber: "JOB-006",
    qNumber: "Q-00006",
    serialNumber: "SN-678901",
    machineRef: "MP-3900",
    status: "pending",
    note: "Abnormal noise during printing",
    team: "Team D",
    col: "COL-006",
    informBy: "email",
    informType: "urgent",
    customer: "Royal Printing Works",
    address1: "90 Station Rd",
    address2: "Ratnapura",
    address3: "Sabaragamuwa Province",
    contact: "+94-45-2233445",
    model: "MP3900",
    sms: false,
    techCode: "TECH006",
    techMobile: "+94-701234572",
  },
  {
    id: "BRK007",
    jobNumber: "JOB-007",
    qNumber: "Q-00007",
    serialNumber: "SN-789123",
    machineRef: "MP-2750",
    status: "assigned",
    note: "Scanner not detecting documents",
    team: "Team A",
    col: "COL-007",
    informBy: "phone",
    informType: "normal",
    customer: "Bright Education Center",
    address1: "34 School Ln",
    address2: "Anuradhapura",
    address3: "North Central Province",
    contact: "+94-25-2233445",
    model: "MP2750",
    sms: true,
    techCode: "TECH007",
    techMobile: "+94-701234573",
  },
  {
    id: "BRK008",
    jobNumber: "JOB-008",
    qNumber: "Q-00008",
    serialNumber: "SN-890234",
    machineRef: "MP-3600",
    status: "completed",
    note: "Print quality faded",
    team: "Team C",
    col: "COL-008",
    informBy: "email",
    informType: "normal",
    customer: "Northern Textiles",
    address1: "11 Factory Rd",
    address2: "Jaffna",
    address3: "Northern Province",
    contact: "+94-21-2233445",
    model: "MP3600",
    sms: false,
    techCode: "TECH008",
    techMobile: "+94-701234574",
  },
  {
    id: "BRK009",
    jobNumber: "JOB-009",
    qNumber: "Q-00009",
    serialNumber: "SN-901345",
    machineRef: "MP-4200",
    status: "pending",
    note: "Error code displayed on startup",
    team: "Team B",
    col: "COL-009",
    informBy: "phone",
    informType: "urgent",
    customer: "Digital Office Solutions",
    address1: "66 Tech Park",
    address2: "Batticaloa",
    address3: "Eastern Province",
    contact: "+94-65-2233445",
    model: "MP4200",
    sms: true,
    techCode: "TECH009",
    techMobile: "+94-701234575",
  },
  {
    id: "BRK010",
    jobNumber: "JOB-010",
    qNumber: "Q-00010",
    serialNumber: "SN-012456",
    machineRef: "MP-5054",
    status: "assigned",
    note: "Fuser unit overheating",
    team: "Team D",
    col: "COL-010",
    informBy: "email",
    informType: "urgent",
    customer: "Metro Supermarket",
    address1: "22 Market Sq",
    address2: "Kalutara",
    address3: "Western Province",
    contact: "+94-34-2233445",
    model: "MP5054",
    sms: false,
    techCode: "TECH010",
    techMobile: "+94-701234576",
  },

  // ... BRK011 → BRK022 (20 new total)
],


serviceScheduleRecallJobs: [
  {
    id: "SCHED001",
    type: "service",
    jobId: "SVC-2024-001",
    customerName: "ABC Corporation",
    location: "Colombo",
    date: "2024-01-15",
    machineRef: "MP-5054",
    technician: "John Silva",
    status: "pending",
  },
  {
    id: "SCHED002",
    type: "breakdown",
    jobId: "BRK-2024-012",
    customerName: "XYZ Industries",
    location: "Kandy",
    date: "2024-01-16",
    machineRef: "MP-2851",
    technician: "Priya Sharma",
    status: "pending",
  },
  {
    id: "SCHED003",
    type: "service",
    jobId: "SVC-2024-002",
    customerName: "Tech Solutions Ltd",
    location: "Galle",
    date: "2024-01-17",
    machineRef: "MP-5054",
    technician: "Miguel Fernandez",
    status: "pending",
  },

  // 🔹 Added 10 more records
  {
    id: "SCHED004",
    type: "service",
    jobId: "SVC-2024-003",
    customerName: "Lanka Traders",
    location: "Negombo",
    date: "2024-01-18",
    machineRef: "MP-4020",
    technician: "Kasun Perera",
    status: "pending",
  },
  {
    id: "SCHED005",
    type: "breakdown",
    jobId: "BRK-2024-013",
    customerName: "Green Farm Pvt Ltd",
    location: "Kurunegala",
    date: "2024-01-18",
    machineRef: "MP-3201",
    technician: "Nimal Jayasinghe",
    status: "pending",
  },
  {
    id: "SCHED006",
    type: "service",
    jobId: "SVC-2024-004",
    customerName: "Oceanic Exports",
    location: "Matara",
    date: "2024-01-19",
    machineRef: "MP-5054",
    technician: "Ruwan Silva",
    status: "pending",
  },
  {
    id: "SCHED007",
    type: "breakdown",
    jobId: "BRK-2024-014",
    customerName: "City Hospital",
    location: "Colombo",
    date: "2024-01-19",
    machineRef: "MP-4100",
    technician: "Saman Kumara",
    status: "pending",
  },
  {
    id: "SCHED008",
    type: "service",
    jobId: "SVC-2024-005",
    customerName: "Bright Education Center",
    location: "Anuradhapura",
    date: "2024-01-20",
    machineRef: "MP-2851",
    technician: "Chathura Fernando",
    status: "pending",
  },
  {
    id: "SCHED009",
    type: "service",
    jobId: "SVC-2024-006",
    customerName: "Northern Textiles",
    location: "Jaffna",
    date: "2024-01-20",
    machineRef: "MP-3900",
    technician: "Arun Kumar",
    status: "pending",
  },
  {
    id: "SCHED010",
    type: "breakdown",
    jobId: "BRK-2024-015",
    customerName: "Metro Supermarket",
    location: "Kalutara",
    date: "2024-01-21",
    machineRef: "MP-2750",
    technician: "Dinesh Weerasinghe",
    status: "pending",
  },
  {
    id: "SCHED011",
    type: "service",
    jobId: "SVC-2024-007",
    customerName: "Royal Printing Works",
    location: "Ratnapura",
    date: "2024-01-21",
    machineRef: "MP-5054",
    technician: "Tharindu Madushan",
    status: "pending",
  },
  {
    id: "SCHED012",
    type: "breakdown",
    jobId: "BRK-2024-016",
    customerName: "Sunrise Garments",
    location: "Avissawella",
    date: "2024-01-22",
    machineRef: "MP-3600",
    technician: "Isuru Bandara",
    status: "pending",
  },
  {
    id: "SCHED013",
    type: "service",
    jobId: "SVC-2024-008",
    customerName: "Digital Office Solutions",
    location: "Batticaloa",
    date: "2024-01-22",
    machineRef: "MP-4200",
    technician: "Mohamed Rizwan",
    status: "pending",
  },
],


technicianBreakdowns: [
  {
    id: "BRK001",
    jobId: "JOB-BRK-001",
    date: "2024-01-15",
    location: "Colombo, Western Province",
    description: "Machine not powering on - MP5054",
    status: "pending",
    daysLeft: 1,
  },
  {
    id: "BRK002",
    jobId: "JOB-BRK-002",
    date: "2024-01-16",
    location: "Kandy, Central Province",
    description: "Paper jam issue - MP2851",
    status: "in-progress",
    daysLeft: 2,
  },

  // 🔹 Added 20 records
  {
    id: "BRK003",
    jobId: "JOB-BRK-003",
    date: "2024-01-17",
    location: "Galle, Southern Province",
    description: "Toner leakage detected - MP4020",
    status: "pending",
    daysLeft: 3,
  },
  {
    id: "BRK004",
    jobId: "JOB-BRK-004",
    date: "2024-01-17",
    location: "Negombo, Western Province",
    description: "Display panel not responding - MP3201",
    status: "completed",
    daysLeft: 0,
  },
  {
    id: "BRK005",
    jobId: "JOB-BRK-005",
    date: "2024-01-18",
    location: "Kurunegala, North Western Province",
    description: "Network printing failure - MP5054",
    status: "pending",
    daysLeft: 2,
  },
  {
    id: "BRK006",
    jobId: "JOB-BRK-006",
    date: "2024-01-18",
    location: "Matara, Southern Province",
    description: "Frequent paper misfeed - MP3900",
    status: "in-progress",
    daysLeft: 1,
  },
  {
    id: "BRK007",
    jobId: "JOB-BRK-007",
    date: "2024-01-19",
    location: "Kalutara, Western Province",
    description: "Scanner not detected - MP2750",
    status: "pending",
    daysLeft: 3,
  },
  {
    id: "BRK008",
    jobId: "JOB-BRK-008",
    date: "2024-01-19",
    location: "Anuradhapura, North Central Province",
    description: "Slow printing speed - MP3600",
    status: "completed",
    daysLeft: 0,
  },
  {
    id: "BRK009",
    jobId: "JOB-BRK-009",
    date: "2024-01-20",
    location: "Jaffna, Northern Province",
    description: "Error code E45 on startup - MP4200",
    status: "pending",
    daysLeft: 4,
  },
  {
    id: "BRK010",
    jobId: "JOB-BRK-010",
    date: "2024-01-20",
    location: "Ratnapura, Sabaragamuwa Province",
    description: "Fuser unit overheating - MP5054",
    status: "in-progress",
    daysLeft: 2,
  },
  {
    id: "BRK011",
    jobId: "JOB-BRK-011",
    date: "2024-01-21",
    location: "Badulla, Uva Province",
    description: "Tray sensor malfunction - MP2851",
    status: "pending",
    daysLeft: 3,
  },
  {
    id: "BRK012",
    jobId: "JOB-BRK-012",
    date: "2024-01-21",
    location: "Avissawella, Western Province",
    description: "Print quality faded - MP4020",
    status: "completed",
    daysLeft: 0,
  },
  {
    id: "BRK013",
    jobId: "JOB-BRK-013",
    date: "2024-01-22",
    location: "Batticaloa, Eastern Province",
    description: "Machine restarting automatically - MP4100",
    status: "pending",
    daysLeft: 5,
  },
  {
    id: "BRK014",
    jobId: "JOB-BRK-014",
    date: "2024-01-22",
    location: "Trincomalee, Eastern Province",
    description: "USB printing not working - MP3201",
    status: "in-progress",
    daysLeft: 2,
  },
  {
    id: "BRK015",
    jobId: "JOB-BRK-015",
    date: "2024-01-23",
    location: "Chilaw, North Western Province",
    description: "Abnormal noise during operation - MP3900",
    status: "pending",
    daysLeft: 4,
  },
  {
    id: "BRK016",
    jobId: "JOB-BRK-016",
    date: "2024-01-23",
    location: "Nuwara Eliya, Central Province",
    description: "Heater error message - MP5054",
    status: "completed",
    daysLeft: 0,
  },
  {
    id: "BRK017",
    jobId: "JOB-BRK-017",
    date: "2024-01-24",
    location: "Hambantota, Southern Province",
    description: "ADF not pulling papers - MP3600",
    status: "pending",
    daysLeft: 3,
  },
  {
    id: "BRK018",
    jobId: "JOB-BRK-018",
    date: "2024-01-24",
    location: "Polonnaruwa, North Central Province",
    description: "Firmware update failed - MP4200",
    status: "in-progress",
    daysLeft: 1,
  },
  {
    id: "BRK019",
    jobId: "JOB-BRK-019",
    date: "2024-01-25",
    location: "Kegalle, Sabaragamuwa Province",
    description: "Power fluctuation damage suspected - MP2750",
    status: "pending",
    daysLeft: 4,
  },
  {
    id: "BRK020",
    jobId: "JOB-BRK-020",
    date: "2024-01-25",
    location: "Vavuniya, Northern Province",
    description: "LAN port not detecting cable - MP4100",
    status: "completed",
    daysLeft: 0,
  },
  {
    id: "BRK021",
    jobId: "JOB-BRK-021",
    date: "2024-01-26",
    location: "Monaragala, Uva Province",
    description: "Print job queue stuck - MP2851",
    status: "pending",
    daysLeft: 2,
  },
  {
    id: "BRK022",
    jobId: "JOB-BRK-022",
    date: "2024-01-26",
    location: "Panadura, Western Province",
    description: "Control board error - MP5054",
    status: "in-progress",
    daysLeft: 1,
  },
],


  technicianServices: [
    {
      id: "SVC001",
      jobId: "JOB-SVC-001",
      customerName: "ABC Corporation",
      date: "2024-01-17",
      location: "Colombo, Western Province",
      daysLeft: 3,
      status: "pending",
    },
    {
      id: "SVC002",
      jobId: "JOB-SVC-002",
      customerName: "XYZ Industries",
      date: "2024-01-18",
      location: "Kandy, Central Province",
      daysLeft: 5,
      status: "pending",
    },
  ],
}
